# Generated by Django 4.2.2 on 2023-07-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebotcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('code_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='UserStock',
        ),
    ]
