# Generated by Django 4.2.2 on 2023-09-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linebotcore', '0003_chatgpt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatGPT',
        ),
    ]
