# Generated by Django 4.2.2 on 2023-09-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebotcore', '0004_delete_chatgpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
