# Generated by Django 4.2.2 on 2023-09-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linebotcore', '0006_historicalrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalRecord',
        ),
    ]
