# Generated by Django 4.2.2 on 2023-09-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebotcore', '0008_historicalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecord',
            name='remark',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
